# Welcome to your prefect.yaml file! You can use this file for storing and managing
# configuration for deploying your flows. We recommend committing this file to source
# control along with your flow code.

# Generic metadata about this project
name: CRDC Data Loader
prefect-version: 2.13.0

# build section allows you to manage and build docker images
build: null

# push section allows you to manage if and how this project is uploaded to remote locations
push: null

# pull section allows you to provide instructions for cloning this project in remote locations

pull:
    - prefect.projects.steps.git_clone_project:
        id: clone-step
        repository: https://github.com/CBIIT/icdc-dataloader.git
        branch: prefect
    - prefect.projects.steps.pip_install_requirements:
        requirements_file: requirements.txt
        directory: "{{ clone-step.directory }}"
        stream_output: False


# the deployments section allows you to provide configuration for deploying flows
deployments:
- name: data-loader
  version: null
  tags: []
  description: null
  entrypoint: hello.py:first_flow
  parameters:
    who: Prefect
  work_pool:
    name: crdc-dh-validation
    work_queue_name: default
    job_variables: {}
  schedule: null
