Config:
  # Manifest file location
  manifest_folder: manifest_file_folder
  # Column names in the manifest file
  file_name: file_name
  file_url: file_location
  file_size: file_size
  file_md5: md5sum
  # If file urls are not available in the manifest, then bucket name and prefix (folder name) need to be provided
  # For each manifest file provided for validation, one set of bucket and prefex needs to be probided
  s3_validation_bucket_list:
    - s3_bucket_1
  s3_validation_prefix_list:
    - s3_prefix_1
  download_from_s3: True
  s3_download_bucket: s3_download_bucket
  s3_download_prefix: s3_download_prefix
  # Output file location, defualt is tmp/
  output_folder: tmp