Config:
  # Manifest file location
  manifest_file: s3://<bucket_name>/<file_key> #i.e. s3://bucket/test/test1.txt
  # Column names in the manifest file
  file_name_column: file_name
  file_url_column: file_location
  file_size_column: file_size
  file_md5_column: md5sum
  # If file urls are not available in the manifest, then bucket name and prefix (folder name) need to be provided
  validation_s3_bucket: bucket
  validation_prefix: prefix